#pragma config(Sensor, dgtl1,  stage1Encoder,  sensorQuadEncoder)
#pragma config(Motor,  port1,           stage1,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "math.h"

////////////////////////////////////////////////////
//    _____                       __  ___         //
//  |_   _|__  __ _ _ __ ___    / /_|___ \ __ _   //
//    | |/ _ \/ _` | '_ ` _ \  |  _ \ __) / _` |  //
//    | |  __/ (_| | | | | | | | (_) / __/ (_| |  //
//    |_|\___|\__,_|_| |_| |_|  \___/_____\__,_|  //
//                                                //
////////////////////////////////////////////////////

float batteryPower;

void towerStage1(int val){
	motor[stage1] = val;
}

void resetLiftEncoders(){
	SensorValue(stage1Encoder) = 0;
}

int followPath = 0;

float motionPIDGraph(long time){
	if(followPath==0){
		if(time<1000)
			return -time*time/600 + 1.7*time;
	}
	else if(followPath==1){
		if(time<1000)
			return -time*time/600 + 1.7*time;
	}
	return 0;
}

int windowSize = 20;
float kP_p1 = 1.2;
float kI_p1 = 0.005;
float kD_p1 = 4;
float kVFF_p1 = 0;
float kP_v1 = 2.6;
float kD_v1 = 10;
long startTime = nPgmTime-10;

bool start = false;
task motionPID(){
	float error_p1 = 0;
	float integral_p1 = 0;
	float derivative_p1 = 0;
	float old_p1 = 0;
	int windowSize = 0;
	float expectedVelocity = 0;
	float velocity = 0;
	float error_v1 = 0;
	float derivative_v1 = 0;
	float old_v1 = 0;
	float drive_v1 = 0;
	long oldTime = nPgmTime-5;
	while(true){
		velocity = (error_p1 - old_p1)/(nPgmTime-oldTime);
		if(start){
			startTime = nPgmTime;
			start = false;
		}
		error_p1 = motionPIDGraph(nPgmTime-startTime+windowSize) - SensorValue(stage1Encoder);
		integral_p1 = integral_p1 + error_p1*(nPgmTime-oldTime);
		derivative_p1 = (error_p1 - old_p1)/(nPgmTime-oldTime);
		if(abs(error_p1)<1 || abs(error_p1)>100){
			integral_p1 = 0;
		}
		old_p1 = error_p1;
		expectedVelocity = limit(error_p1 * kP_p1 + integral_p1 * kI_p1 + derivative_p1 * kD_p1 + kVFF_p1 * velocity, -127, 127);
		/**error_v1 = motionPIDGraph(nPgmTime-startTime) - SensorValue(stage1Encoder);
		derivative_v1 = (error_v1 - old_v1)/(nPgmTime-oldTime);
		old_v1 = error_v1;
		drive_v1 = drive_v1 + error_p1 * kP_v1 + derivative_p1 * kD_v1;
		towerStage1(drive_v1);*/
		towerStage1(expectedVelocity);
		oldTime = nPgmTime;
		delay(20);
	}
}

task dataLog(){
	datalogClear();
	datalogStart();
	while(true){
		datalogAddValueWithTimeStamp(0, motionPIDGraph(nPgmTime-startTime+windowSize));
		datalogAddValueWithTimeStamp(1, motionPIDGraph(nPgmTime-startTime));
		datalogAddValueWithTimeStamp(2, SensorValue(stage1Encoder));
		datalogAddValueWithTimeStamp(3, motor[stage1]);
		batteryPower = nImmediateBatteryLevel;
		wait1Msec(10);
	}
}

void pre_auton(){}

task autonomous(){}

task usercontrol(){
	resetLiftEncoders();
	startTask(dataLog);
	startTask(motionPID);
	while(true){
		if(vexRT[Btn8U]){
			followPath = 0;
			start=true;
			wait1Msec(500);
		}
		if(vexRT[Btn8R]){
			followPath = 1;
			start=true;
			wait1Msec(500);
		}
	}
}
